src/PlagiarismCompare.Web/Controllers/CFileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class CFileController : Controller
{
    private readonly DataContext _context;

    public CFileController(DataContext context)
    {
        _context = context;
    }
    
    // GET
    public async Task<IActionResult> Index()
    {
        return View(await _context.CFiles
            .Include(c => c.Submission)
            .ThenInclude(s => s.SemesterStudent)
            .ThenInclude(s => s.Semester)
            .ThenInclude(s => s.Module)
            .Include(c => c.Submission)
            .ThenInclude(s => s.SemesterStudent)
            .ThenInclude(s => s.Student)
            .ToListAsync());
    }
    
    // GET: CFile/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cFile = await _context.CFiles
            // Main file module
            .Include(c => c.Submission)
            .ThenInclude(s => s.SemesterStudent)
            .ThenInclude(s => s.Semester)
            .ThenInclude(s=> s.Module)
            // Main file student
            .Include(c => c.Submission)
            .ThenInclude(s => s.SemesterStudent)
            .ThenInclude(s => s.Student)
            .FirstOrDefaultAsync(m => m.Id == id);

        if (cFile == null)
        {
            return NotFound();
        }
        
        // Get 50 top results
        IQueryable<ComparisonResult> comparisonResults = _context.ComparisonResults
            // Other file module
            .Include(c => c.CFiles)
            .ThenInclude(c => c.Submission)
            .ThenInclude(s => s.SemesterStudent)
            .ThenInclude(s => s.Semester)
            .ThenInclude(s => s.Module)
            // Other file student
            .Include(c => c.CFiles)
            .ThenInclude(c => c.Submission)
            .ThenInclude(s => s.SemesterStudent)
            .ThenInclude(s => s.Student)
            .Where(r => r.CFiles.Contains(cFile) && r.LongestTokenMatch > 0)
            .Distinct()
            .OrderByDescending(r => r.LongestTokenMatch)
            .Take(50);

        ViewBag.ComparisonResults = comparisonResults;

        string reports = JsonConvert.SerializeObject(comparisonResults);
        ViewBag.Reports = reports;
        
        return View(cFile);
    }
}

src/PlagiarismCompare.Web/Controllers/ModuleController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class ModuleController : Controller
{
    private readonly DataContext _context;

    public ModuleController(DataContext context)
    {
        _context = context;
    }

    // GET: Module
    public async Task<IActionResult> Index()
    {
        return View(await _context.Modules.ToListAsync());
    }

    // GET: Module/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @module = await _context.Modules
            .Include(s=> s.Semesters)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (@module == null)
        {
            return NotFound();
        }

        return View(@module);
    }

    // GET: Module/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Module/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Code,Name,Id")] Module @module)
    {
        if (ModelState.IsValid)
        {
            _context.Add(@module);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(@module);
    }

    // GET: Module/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @module = await _context.Modules.FindAsync(id);
        if (@module == null)
        {
            return NotFound();
        }
        return View(@module);
    }

    // POST: Module/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Code,Name,Id")] Module @module)
    {
        if (id != @module.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(@module);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ModuleExists(@module.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(@module);
    }

    // GET: Module/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @module = await _context.Modules
            .FirstOrDefaultAsync(m => m.Id == id);
        if (@module == null)
        {
            return NotFound();
        }

        return View(@module);
    }

    // POST: Module/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var @module = await _context.Modules.FindAsync(id);
        if (@module == null)
        {
            return NotFound();
        }
        
        _context.Modules.Remove(@module);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool ModuleExists(int id)
    {
        return _context.Modules.Any(e => e.Id == id);
    }
}

src/PlagiarismCompare.Web/Controllers/SemesterController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class SemesterController : Controller
{
    private readonly DataContext _context;

    public SemesterController(DataContext context)
    {
        _context = context;
    }

    // GET: Semester
    public async Task<IActionResult> Index()
    {
        return View(await _context.ModuleSemesters.Include(s => s.Module).ToListAsync());
    }

    // GET: Semester/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .Include(s => s.SemesterStudents)
            .ThenInclude(s => s.Student)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (semester == null)
        {
            return NotFound();
        }

        return View(semester);
    }

    // GET: Semester/Create/5
    public async Task<IActionResult> Create(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var module = await _context.Modules.FirstOrDefaultAsync(m => m.Id == id);
        if (module == null)
        {
            return NotFound();
        }

        ViewBag.Module = module;
        return View();
    }

    // POST: Semester/Create/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int id, [Bind("Year,Term")] Semester semester)
    {
        var module = await _context.Modules.FirstOrDefaultAsync(m => m.Id == id);
        if (module == null)
        {
            return NotFound();
        }

        semester.Module = module;
        ModelState.Remove("Module");

        if (ModelState.IsValid)
        {
            _context.Add(semester);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
            
        ViewBag.Module = module;
        return View(semester);
    }

    // GET: Semester/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
            
        if (semester == null)
        {
            return NotFound();
        }
        return View(semester);
    }

    // POST: Semester/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Year,Term,Id")] Semester semester)
    {
        if (id != semester.Id)
        {
            return NotFound();
        }
            
        ModelState.Remove("Module");
        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(semester);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SemesterExists(semester.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
            
        semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        return View(semester);
    }

    // GET: Semester/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semester = await _context.ModuleSemesters.FirstOrDefaultAsync(m => m.Id == id);
        if (semester == null)
        {
            return NotFound();
        }

        return View(semester);
    }

    // POST: Semester/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var semester = await _context.ModuleSemesters.FindAsync(id);
        if (semester == null)
        {
            return NotFound();
        }
        
        _context.ModuleSemesters.Remove(semester);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool SemesterExists(int id)
    {
        return _context.ModuleSemesters.Any(e => e.Id == id);
    }
}

src/PlagiarismCompare.Web/Controllers/StudentController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class StudentController : Controller
{
    private readonly DataContext _context;

    public StudentController(DataContext context)
    {
        _context = context;
    }

    // GET: Student
    public async Task<IActionResult> Index()
    {
        return View(await _context.Students.ToListAsync());
    }

    // GET: Student/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var student = await _context.Students
            .Include(s=> s.SemesterStudents)
            .ThenInclude(s=> s.Semester)
            .ThenInclude(s => s.Module)
            .Include(s => s.SemesterStudents)
            .ThenInclude(s => s.Submissions)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (student == null)
        {
            return NotFound();
        }

        return View(student);
    }

    // GET: Student/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Student/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("FirstName,LastName,Code,StudentId,Id")] Student student)
    {
        if (!ModelState.IsValid)
        {
            return View(student);
        }
        
        _context.Add(student);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    // GET: Student/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var student = await _context.Students.FindAsync(id);
        if (student == null)
        {
            return NotFound();
        }
        return View(student);
    }

    // POST: Student/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Code,StudentId,Id")] Student student)
    {
        if (id != student.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(student);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(student.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(student);
    }

    // GET: Student/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var student = await _context.Students.FirstOrDefaultAsync(m => m.Id == id);
        if (student == null)
        {
            return NotFound();
        }

        return View(student);
    }

    // POST: Student/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var student = await _context.Students.FindAsync(id);
        if (student == null)
        {
            return NotFound();
        }
        
        _context.Students.Remove(student);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool StudentExists(int id)
    {
        return _context.Students.Any(e => e.Id == id);
    }
}

src/PlagiarismCompare.Web/Views/CFile/Details.cshtml
@using PlagiarismCompare.Data.Models
@model PlagiarismCompare.Data.Models.CFile

@{
    ViewData["Title"] = "Details";
    var submission = Model.Submission;
    var semester = submission.SemesterStudent.Semester;
    var module = semester.Module;
    var student = submission.SemesterStudent.Student;

    IQueryable<ComparisonResult> comparisonResults = ViewBag.ComparisonResults;
    string reports = ViewBag.Reports;
}

@section Head
{
    <style>
        .codeLine {
            color: black;
            display: block;
        }
        
        code .codeLine::before {
            color: red;
            content: attr(line-number);
            padding-right: 1em;
        }
    </style>
}

<h1>File Details</h1>

<div>
    <h4>Comparison results</h4>
    <hr/>
    <table class="table">
        <thead>
        <tr>
            <th>Other file path</th>
            <th># Characters</th>
            <th># Lines</th>
            <th># Tokens</th>
            <th>Longest token match</th>
            <th>Similarity</th>
            <th>Error?</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @{ int i = 0; }
        @foreach (var comparisonResult in comparisonResults)
        {
            var otherFile = comparisonResult.GetOtherCFile(Model);
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => otherFile.FilePath)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => otherFile.NumCharacters)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => otherFile.NumLines)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => otherFile.NumTokens)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => comparisonResult.LongestTokenMatch)
                </td>
                <td>
                    @comparisonResult.Similarity.ToString("P")
                </td>
                <td>
                    @Html.DisplayName(otherFile.Error != null ? "Yes" : "No")
                </td>
                <td>
                    <a href="#" data-id="@i" data-other-file-id="@otherFile.Id" class="compare-link">Compare</a> |
                    <a asp-controller="CFile" asp-action="Details" asp-route-id="@otherFile.Id">File details</a>
                </td>
            </tr>
            i++;
        }
        @if (!comparisonResults.Any())
        {
            <tr>
                <td colspan="8">No files found</td>
            </tr>
        }
        </tbody>
    </table>
</div>

<div class="mt-3">
    <table class="table">
        <thead>
        <tr>
            <th>Details</th>
            <th>Selected file</th>
            <th>Other file</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">Module code</th>
            <td>
                <a asp-controller="Module" asp-action="Details" asp-route-id="@module.Id">
                    @Html.DisplayFor(model => module.Code)
                </a>
            </td>
            <td id="otherFileModuleCode"></td>
        </tr>
        <tr>
            <th scope="row">Module name</th>
            <td>@Html.DisplayFor(model => module.Name)</td>
            <td id="otherFileModuleName"></td>
        </tr>
        <tr>
            <th scope="row">Semester year</th>
            <td>@Html.DisplayFor(model => semester.Year)</td>
            <td id="otherFileSemesterYear"></td>
        </tr>
        <tr>
            <th scope="row">Semester term</th>
            <td>
                <a asp-controller="Semester" asp-action="Details" asp-route-id="@semester.Id">
                    @Html.DisplayFor(model => semester.Term)
                </a>
            </td>
            <td id="otherFileSemesterTerm"></td>
        </tr>
        <tr>
            <th scope="row">Student name</th>
            <td>@Html.DisplayFor(model => student.Name)</td>
            <td id="otherFileStudentName"></td>
        </tr>
        <tr>
            <th scope="row">Student ID</th>
            <td>
                <a asp-controller="Student" asp-action="Details" asp-route-id="@student.Id">
                    @Html.DisplayFor(model => student.StudentId)
                </a>
            </td>
            <td id="otherFileStudentId"></td>
        </tr>
        <tr>
            <th scope="row">Submission name</th>
            <td>
                <a asp-controller="Submission" asp-action="Details" asp-route-id="@submission.Id">
                    @Html.DisplayFor(model => submission.Name)
                </a>
            </td>
            <td id="otherFileSubmissionName"></td>
        </tr>
        <tr>
            <th scope="row">@Html.DisplayNameFor(model => submission.State)</th>
            <td>@Html.DisplayFor(model => submission.State)</td>
            <td id="otherFileSubmissionState"></td>
        </tr>
        <tr>
            <th scope="row">@Html.DisplayNameFor(model => submission.Submitted)</th>
            <td>@Html.DisplayFor(model => submission.Submitted)</td>
            <td id="otherFileSubmissionSubmitted"></td>
        </tr>
        <tr>
            <th scope="row">@Html.DisplayNameFor(model => Model.FilePath)</th>
            <td>@Html.DisplayFor(model => Model.FilePath)</td>
            <td id="otherFileFilePath"></td>
        </tr>
        <tr>
            <th scope="row">@Html.DisplayNameFor(model => Model.NumCharacters)</th>
            <td>@Html.DisplayFor(model => Model.NumCharacters)</td>
            <td id="otherFileNumCharacters"></td>
        </tr>
        <tr>
            <th scope="row">@Html.DisplayNameFor(model => Model.NumLines)</th>
            <td>@Html.DisplayFor(model => Model.NumLines)</td>
            <td id="otherFileNumLines"></td>
        </tr>
        <tr>
            <th scope="row">@Html.DisplayNameFor(model => Model.NumTokens)</th>
            <td>@Html.DisplayFor(model => Model.NumTokens)</td>
            <td id="otherFileNumTokens"></td>
        </tr>
        </tbody>
    </table>
</div>

<div class="mt-3">
    <table class="table" id="tokensTable">
        <thead>
        <tr>
            <th>Selected file line start</th>
            <th>Other file line start</th>
            <th>Number matching tokens</th>
            <th>View matching tokens</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<div class="mt-3">
    <h5>Matching tokens</h5>
    
    <h6>Selected file</h6>
    <code id="mainMatchingTokensCode" class="d-block bg-light"></code>
    
    <h6 class="mt-3">Other file</h6>
    <code id="otherMatchingTokensCode" class="d-block bg-light"></code>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

<div class="modal-dialog modal-xl">

</div>

@section Scripts
{
    <script>
    let currentFileId = @Html.Raw(Model.Id)
    let comparisonReports = @Html.Raw(reports)
    </script>

    <script>
    let updateDetailsTable = function(otherFile) {
        let moduleLinkTag = $('<a></a>');
        moduleLinkTag.text(otherFile.Submission.SemesterStudent.Semester.Module.Code);
        let moduleLink = `@Url.Action("Details", "Module")/${otherFile.Submission.SemesterStudent.Semester.Module.Id}`;
        moduleLinkTag.attr('href', moduleLink);
        $('#otherFileModuleCode').html(moduleLinkTag);
        
        $('#otherFileModuleName').text(otherFile.Submission.SemesterStudent.Semester.Module.Name);
        $('#otherFileSemesterYear').text(otherFile.Submission.SemesterStudent.Semester.Year);
        
        let semesterLinkTag = $('<a></a>');
        semesterLinkTag.text(otherFile.Submission.SemesterStudent.Semester.Term);
        let semesterLink = `@Url.Action("Details", "Semester")/${otherFile.Submission.SemesterStudent.Semester.Id}`;
        semesterLinkTag.attr('href', semesterLink);
        $('#otherFileSemesterTerm').html(semesterLinkTag);
        
        $('#otherFileStudentName').text(otherFile.Submission.SemesterStudent.Student.Name);
        
        let studentLinkTag = $('<a></a>');
        studentLinkTag.text(otherFile.Submission.SemesterStudent.Student.StudentId);
        let studentLink = `@Url.Action("Details", "Student")/${otherFile.Submission.SemesterStudent.Student.Id}`;
        studentLinkTag.attr('href', studentLink);
        $('#otherFileStudentId').html(studentLinkTag);
        
        let submissionLinkTag = $('<a></a>');
        submissionLinkTag.text(otherFile.Submission.Name);
        let submissionLink = `@Url.Action("Details", "Submission")/${otherFile.Submission.Id}`;
        submissionLinkTag.attr('href', submissionLink);
        $('#otherFileSubmissionName').html(submissionLinkTag);
        
        $('#otherFileSubmissionState').text(otherFile.Submission.State);
        $('#otherFileSubmissionSubmitted').text(new Date(otherFile.Submission.Submitted).toLocaleString());
        $('#otherFileFilePath').text(otherFile.FilePath);
        $('#otherFileNumCharacters').text(otherFile.NumCharacters);
        $('#otherFileNumLines').text(otherFile.NumLines);
        $('#otherFileNumTokens').text(otherFile.NumTokens);
    };
    
    let updateTokensTable = function(report, reportIndex) {
        let mainFileFirst = report.MatchesMain === currentFileId;
        let mainTokenMatchIndexStart = mainFileFirst ? "FileATokenIndexStart" : "FileBTokenIndexStart";
        let otherTokenMatchIndexStart = mainFileFirst ? "FileBTokenIndexStart" : "FileATokenIndexStart";
        
        let tokensTableBody = $('#tokensTable tbody');
        tokensTableBody.empty();
        
        report.Matches.forEach(function(match) {
            let mainTokenStart = match[mainTokenMatchIndexStart];
            let otherTokenStart = match[otherTokenMatchIndexStart];
            let numMatchingTokens = match.NumberMatchingTokens;
            
            // Database result always in that order
            let mainFirstToken = report.CFiles[1].Tokens[mainTokenStart];
            let otherFirstToken = report.CFiles[0].Tokens[otherTokenStart];
            
            let newRow = $('<tr></tr>');
            newRow.append(`<td>${mainFirstToken.lineNumber}</td>`);
            newRow.append(`<td>${otherFirstToken.lineNumber}</td>`);
            newRow.append(`<td>${numMatchingTokens}</td>`);
            newRow.append(`<td> <a href="#" data-report-index="${reportIndex}" data-main-token-index="${mainTokenStart}" data-other-token-index="${otherTokenStart}" data-num-tokens="${numMatchingTokens}" class="view-tokens-link">View tokens</a></td>`);
            
            tokensTableBody.append(newRow);
        });
    };
    
    $('.compare-link').on('click', function(event) {
        event.preventDefault();
        
        let reportIndex = parseInt($(this).attr('data-id'));
        let report = comparisonReports[reportIndex];
        
        let mainFile = report['CFiles'][1];
        let otherFile = report['CFiles'][0];
            
        updateDetailsTable(otherFile);
        updateTokensTable(report, reportIndex);
        
        registerViewTokens();
        $('#matchingTokensCode').empty();
    });
    
    let populateCodeBox = function (codeBox, tokens) {
        codeBox.empty();
                    
        let lineNumber = tokens[0].lineNumber;
        let lineSpan = $('<span />').addClass('codeLine').attr('line-number', lineNumber);;
        let lineText = '';
        
        tokens.forEach(function (token) {
            while (token.lineNumber > lineNumber) {
                lineSpan.text(lineText)
                lineText = '';
                
                codeBox.append(lineSpan);
                
                lineNumber += 1;
                lineSpan = $('<span />').addClass('codeLine').attr('line-number', lineNumber);
            }

            lineText += token.text + ' ';
        });
        lineSpan.text(lineText);
        codeBox.append(lineSpan);
    };
    
    let registerViewTokens = function () {
        $('.view-tokens-link').on('click', function(event) {
            event.preventDefault();
            
            let reportIndex = parseInt($(this).attr('data-report-index'));
            let report = comparisonReports[reportIndex];
            
            let mainTokensStartIndex = parseInt($(this).attr('data-main-token-index'));
            let otherTokensStartIndex = parseInt($(this).attr('data-other-token-index'));
            let numMatchingTokens = parseInt($(this).attr('data-num-tokens'));
            
            let mainFile = report['CFiles'][1];
            let otherFile = report['CFiles'][0];
            
            populateCodeBox($('#mainMatchingTokensCode'), mainFile.Tokens.slice(mainTokensStartIndex, mainTokensStartIndex + numMatchingTokens));
            populateCodeBox($('#otherMatchingTokensCode'), otherFile.Tokens.slice(otherTokensStartIndex, otherTokensStartIndex + numMatchingTokens));
            
        });
    };

    </script>
}