src/PlagiarismCompare.Web/Controllers/SemesterController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class SemesterController : Controller
{
    private readonly DataContext _context;

    public SemesterController(DataContext context)
    {
        _context = context;
    }

    // GET: Semester
    public async Task<IActionResult> Index()
    {
        return View(await _context.ModuleSemesters.Include(s => s.Module).ToListAsync());
    }

    // GET: Semester/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .Include(s => s.SemesterStudents)
            .ThenInclude(s => s.Student)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (semester == null)
        {
            return NotFound();
        }

        return View(semester);
    }

    // GET: Semester/Create/5
    public async Task<IActionResult> Create(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var module = await _context.Modules.FirstOrDefaultAsync(m => m.Id == id);
        if (module == null)
        {
            return NotFound();
        }

        ViewBag.Module = module;
        return View();
    }

    // POST: Semester/Create/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int id, [Bind("Year,Term")] Semester semester)
    {
        var module = await _context.Modules.FirstOrDefaultAsync(m => m.Id == id);
        if (module == null)
        {
            return NotFound();
        }

        semester.Module = module;
        ModelState.Remove("Module");

        if (ModelState.IsValid)
        {
            _context.Add(semester);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
            
        ViewBag.Module = module;
        return View(semester);
    }

    // GET: Semester/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
            
        if (semester == null)
        {
            return NotFound();
        }
        return View(semester);
    }

    // POST: Semester/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Year,Term,Id")] Semester semester)
    {
        if (id != semester.Id)
        {
            return NotFound();
        }
            
        ModelState.Remove("Module");
        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(semester);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SemesterExists(semester.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
            
        semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        return View(semester);
    }

    // GET: Semester/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semester = await _context.ModuleSemesters.FirstOrDefaultAsync(m => m.Id == id);
        if (semester == null)
        {
            return NotFound();
        }

        return View(semester);
    }

    // POST: Semester/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var semester = await _context.ModuleSemesters.FindAsync(id);
        if (semester == null)
        {
            return NotFound();
        }
        
        _context.ModuleSemesters.Remove(semester);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool SemesterExists(int id)
    {
        return _context.ModuleSemesters.Any(e => e.Id == id);
    }
}

src/PlagiarismCompare.Web/Controllers/SemesterStudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;
using PlagiarismCompare.Web.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class SemesterStudentController : Controller
{
    private readonly DataContext _context;

    public SemesterStudentController(DataContext context)
    {
        _context = context;
    }
    
    public async Task<IActionResult> CreateFromStudent(int id)
    {
        var student = await _context.Students.FindAsync(id);
        if (student == null)
        {
            return NotFound();
        }

        var possibleSemesters = _context.ModuleSemesters
            .Include(s => s.Module)
            .Where(s => s.SemesterStudents.All(x => x.Student.Id != student.Id));

        ViewBag.student = student;
        ViewBag.possibleSemesters = possibleSemesters;
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateFromStudent(int id, [Bind("SemesterId")] SemesterStudentCreateForm semesterStudentForm)
    {
        var student = await _context.Students.FindAsync(id);
        if (student == null)
        {
            return NotFound();
        }

        var possibleSemesters = _context.ModuleSemesters
            .Include(s => s.Module)
            .Where(s => s.SemesterStudents.All(x => x.Student.Id != student.Id));
        
        var semester = possibleSemesters.FirstOrDefault(s => s.Id == semesterStudentForm.SemesterId);
        if (semester == null)
        {
            ModelState.AddModelError("SemesterId", "Invalid semester");
        }
        
        ModelState.Remove("StudentId");
        if (!ModelState.IsValid || semester == null)
        {
            ViewBag.student = student;
            ViewBag.possibleSemesters = possibleSemesters;
            return View(semesterStudentForm);
        }

        student.SemesterStudents.Add(new SemesterStudent()
        {
            Semester = semester
        });
        await _context.SaveChangesAsync();
        
        return RedirectToAction(nameof(StudentController.Details), "Student",new {id = student.Id});
    }
    
    public async Task<IActionResult> CreateFromSemester(int id)
    {
        var semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (semester == null)
        {
            return NotFound();
        }

        var possibleStudents = _context.Students.AsQueryable()
            .Where(s => s.SemesterStudents.All(x => x.Semester.Id != semester.Id));

        ViewBag.semester = semester;
        ViewBag.possibleStudents = possibleStudents;
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateFromSemester(int id, [Bind("StudentId")] SemesterStudentCreateForm semesterStudentForm)
    {
        var semester = await _context.ModuleSemesters
            .Include(s => s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (semester == null)
        {
            return NotFound();
        }

        var possibleStudents = _context.Students.AsQueryable().Where(s => s.SemesterStudents.All(x => x.Semester.Id != id));
        var student = possibleStudents.FirstOrDefault(s => s.Id == semesterStudentForm.StudentId);
        if (student == null)
        {
            ModelState.AddModelError("StudentId", "Invalid student");
        }
        
        ModelState.Remove("SemesterId");
        if (!ModelState.IsValid)
        {
            ViewBag.semester = semester;
            ViewBag.possibleStudents = possibleStudents;
            return View(semesterStudentForm);
        }

        semester.SemesterStudents.Add(new SemesterStudent()
        {
            Student = student!
        });
        await _context.SaveChangesAsync();
        
        return RedirectToAction(nameof(SemesterController.Details), "Semester",new {id = semester.Id});
    }
    
    // GET: SemesterStudent/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semesterStudent = await _context.SemesterStudents
            .Include(s => s.Student)
            .Include(s => s.Semester)
            .ThenInclude(s => s.Module)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (semesterStudent == null)
        {
            return NotFound();
        }

        return View(semesterStudent);
    }

    // POST: SemesterStudent/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var semesterStudent = await _context.SemesterStudents
            .Include(s => s.Student)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (semesterStudent == null)
        {
            return NotFound();
        }
        
        _context.SemesterStudents.Remove(semesterStudent);
        await _context.SaveChangesAsync();
        
        return RedirectToAction(nameof(StudentController.Details), "Student", new {id = semesterStudent.Student.Id});
    }
}

src/PlagiarismCompare.Web/Controllers/SubmissionController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Services;
using PlagiarismCompare.Services.IO;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;
using PlagiarismCompare.Web.BackgroundServices;
using PlagiarismCompare.Web.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class SubmissionController : Controller
{
    private readonly DataContext _context;
    private readonly SubmissionUploadHandler _uploadHandler;
    private readonly SubmissionComparisonHandler _comparisonHandler;
    private readonly SubmissionComparisonQueue _comparisonQueue;

    public SubmissionController(DataContext context, SubmissionUploadHandler uploadHandler, SubmissionComparisonHandler comparisonHandler, SubmissionComparisonQueue comparisonQueue)
    {
        _context = context;
        _uploadHandler = uploadHandler;
        _comparisonHandler = comparisonHandler;
        _comparisonQueue = comparisonQueue;
    }

    // GET: Submission
    public async Task<IActionResult> Index()
    {
        return View(await _context.Submissions
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Semester)
            .ThenInclude(s=> s.Module)
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Student)
            .ToListAsync());
    }

    // GET: Submission/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var submission = await _context.Submissions
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Semester)
            .ThenInclude(s=> s.Module)
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Student)
            .Include(s => s.CFiles)
            .ThenInclude(c => c.ComparisonResults)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (submission == null)
        {
            return NotFound();
        }

        return View(submission);
    }

    // GET: Submission/Create/5
    public async Task<IActionResult> Create(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semesterStudent = await _context.SemesterStudents
            .Include(s=> s.Student)
            .Include(s=> s.Semester)
            .ThenInclude(s=> s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (semesterStudent == null)
        {
            return NotFound();
        }

        ViewBag.SemesterStudent = semesterStudent;
        return View(new SubmissionForm());
    }

    // POST: Submission/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int id, [Bind("Name,ZipFile")] SubmissionForm submissionForm)
    {
        var semesterStudent = await _context.SemesterStudents
            .Include(s=> s.Student)
            .Include(s=> s.Semester)
            .ThenInclude(s=> s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (semesterStudent == null)
        {
            return NotFound();
        }
        
        if (!ModelState.IsValid)
        {
            ViewBag.SemesterStudent = semesterStudent;
            return View(submissionForm);
        }
        
        string fileNamePrefix = $"{semesterStudent.Student.Code}_{semesterStudent.Semester.Module.Code}";
        var submission = await _uploadHandler.ParseSubmission(submissionForm.Name, fileNamePrefix, submissionForm.ZipFile.OpenReadStream(),
            semesterStudent);

        // Compare submission with all other submissions
        _comparisonQueue.Enqueue(submission);

        return RedirectToAction(nameof(Details), new {Id = submission.Id});
    }

    // GET: Submission/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var submission = await _context.Submissions.FirstOrDefaultAsync(m => m.Id == id);
        if (submission == null)
        {
            return NotFound();
        }

        return View(submission);
    }

    // POST: Submission/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var submission = await _context.Submissions
            .Include(s => s.CFiles)
            .ThenInclude(c => c.ComparisonResults)
            .FirstOrDefaultAsync(s => s.Id == id);
        
        if (submission == null)
        {
            return NotFound();
        }
        
        foreach (var cFile in submission.CFiles) {
            foreach (var comparisonResult in cFile.ComparisonResults)
            {
                _context.ComparisonResults.Remove(comparisonResult);
            }
        }
        await _context.SaveChangesAsync();

        _context.Submissions.Remove(submission);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

src/PlagiarismCompare.Web/Views/Student/Create.cshtml
@model PlagiarismCompare.Data.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create Student</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group my-2">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="StudentId" class="control-label"></label>
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


src/PlagiarismCompare.Web/Views/Student/Delete.cshtml
@model PlagiarismCompare.Data.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Student</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/PlagiarismCompare.Web/Views/Student/Details.cshtml
@model PlagiarismCompare.Data.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h1>Student Details</h1>

<div>
    <h4>Student</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StudentId)
        </dd>
    </dl>
</div>

<div>
    <h4>Enrolled semesters</h4>
    <p>
        <a asp-controller="SemesterStudent" asp-action="CreateFromStudent" asp-route-id="@Model.Id">Enrol in semester</a>
    </p>
    <hr/>
    <table class="table">
        <thead>
        <tr>
            <th>Module Code</th>
            <th>Module Name</th>
            <th>Year</th>
            <th>Term</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var semesterStudent in Model.SemesterStudents)
        {
            var semester = semesterStudent.Semester;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => semester.Module.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => semester.Module.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => semester.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => semester.Term)
                </td>
                <td>
                    <a asp-controller="Submission" asp-action="Create" asp-route-id="@semesterStudent.Id">Create submission</a> |
                    <a asp-controller="Semester" asp-action="Details" asp-route-id="@semester.Id">Semester details</a> |
                    <a asp-controller="SemesterStudent" asp-action="Delete" asp-route-id="@semesterStudent.Id">Unenrol</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

<div>
    <h4>Submissions</h4>
    <hr/>

    <table class="table">
        <thead>
        <tr>
            <th colspan="2">
                Module
            </th>
            <th colspan="2">
                Semester
            </th>
            <th colspan="3">
                Submission
            </th>
            <th></th>
        </tr>
        <tr>
            <th>
                Code
            </th>
            <th>
                Name
            </th>
            <th>
                Year
            </th>
            <th>
                Term
            </th>
            <th>
                Name
            </th>
            <th>
                State
            </th>
            <th>
                Submitted
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var semesterStudent in Model.SemesterStudents)
        {
            @foreach (var submission in semesterStudent.Submissions)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => submission.SemesterStudent.Semester.Module.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => submission.SemesterStudent.Semester.Module.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => submission.SemesterStudent.Semester.Year)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => submission.SemesterStudent.Semester.Term)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => submission.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => submission.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => submission.Submitted)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@submission.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@submission.Id">Delete</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to students list</a>
</div>

src/PlagiarismCompare.Web/Views/Student/Edit.cshtml
@model PlagiarismCompare.Data.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Student</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group my-2">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="StudentId" class="control-label"></label>
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group my-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


src/PlagiarismCompare.Web/Views/Student/Index.cshtml
@model IEnumerable<PlagiarismCompare.Data.Models.Student>

@{
    ViewData["Title"] = "Students";
}

<h1>Students</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>