src/PlagiarismCompare.Web/Controllers/ModuleController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class ModuleController : Controller
{
    private readonly DataContext _context;

    public ModuleController(DataContext context)
    {
        _context = context;
    }

    // GET: Module
    public async Task<IActionResult> Index()
    {
        return View(await _context.Modules.ToListAsync());
    }

    // GET: Module/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @module = await _context.Modules
            .Include(s=> s.Semesters)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (@module == null)
        {
            return NotFound();
        }

        return View(@module);
    }

    // GET: Module/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Module/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Code,Name,Id")] Module @module)
    {
        if (ModelState.IsValid)
        {
            _context.Add(@module);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(@module);
    }

    // GET: Module/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @module = await _context.Modules.FindAsync(id);
        if (@module == null)
        {
            return NotFound();
        }
        return View(@module);
    }

    // POST: Module/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Code,Name,Id")] Module @module)
    {
        if (id != @module.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(@module);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ModuleExists(@module.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(@module);
    }

    // GET: Module/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @module = await _context.Modules
            .FirstOrDefaultAsync(m => m.Id == id);
        if (@module == null)
        {
            return NotFound();
        }

        return View(@module);
    }

    // POST: Module/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var @module = await _context.Modules.FindAsync(id);
        if (@module == null)
        {
            return NotFound();
        }
        
        _context.Modules.Remove(@module);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool ModuleExists(int id)
    {
        return _context.Modules.Any(e => e.Id == id);
    }
}

src/PlagiarismCompare.Web/Controllers/StudentController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class StudentController : Controller
{
    private readonly DataContext _context;

    public StudentController(DataContext context)
    {
        _context = context;
    }

    // GET: Student
    public async Task<IActionResult> Index()
    {
        return View(await _context.Students.ToListAsync());
    }

    // GET: Student/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var student = await _context.Students
            .Include(s=> s.SemesterStudents)
            .ThenInclude(s=> s.Semester)
            .ThenInclude(s => s.Module)
            .Include(s => s.SemesterStudents)
            .ThenInclude(s => s.Submissions)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (student == null)
        {
            return NotFound();
        }

        return View(student);
    }

    // GET: Student/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Student/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("FirstName,LastName,Code,StudentId,Id")] Student student)
    {
        if (!ModelState.IsValid)
        {
            return View(student);
        }
        
        _context.Add(student);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    // GET: Student/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var student = await _context.Students.FindAsync(id);
        if (student == null)
        {
            return NotFound();
        }
        return View(student);
    }

    // POST: Student/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Code,StudentId,Id")] Student student)
    {
        if (id != student.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(student);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(student.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(student);
    }

    // GET: Student/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var student = await _context.Students.FirstOrDefaultAsync(m => m.Id == id);
        if (student == null)
        {
            return NotFound();
        }

        return View(student);
    }

    // POST: Student/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var student = await _context.Students.FindAsync(id);
        if (student == null)
        {
            return NotFound();
        }
        
        _context.Students.Remove(student);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool StudentExists(int id)
    {
        return _context.Students.Any(e => e.Id == id);
    }
}

src/PlagiarismCompare.Web/Controllers/SubmissionController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlagiarismCompare.Services;
using PlagiarismCompare.Services.IO;
using PlagiarismCompare.Data;
using PlagiarismCompare.Data.Models;
using PlagiarismCompare.Web.BackgroundServices;
using PlagiarismCompare.Web.Models;

namespace PlagiarismCompare.Web.Controllers;

[Authorize]
public class SubmissionController : Controller
{
    private readonly DataContext _context;
    private readonly SubmissionUploadHandler _uploadHandler;
    private readonly SubmissionComparisonHandler _comparisonHandler;
    private readonly SubmissionComparisonQueue _comparisonQueue;

    public SubmissionController(DataContext context, SubmissionUploadHandler uploadHandler, SubmissionComparisonHandler comparisonHandler, SubmissionComparisonQueue comparisonQueue)
    {
        _context = context;
        _uploadHandler = uploadHandler;
        _comparisonHandler = comparisonHandler;
        _comparisonQueue = comparisonQueue;
    }

    // GET: Submission
    public async Task<IActionResult> Index()
    {
        return View(await _context.Submissions
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Semester)
            .ThenInclude(s=> s.Module)
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Student)
            .ToListAsync());
    }

    // GET: Submission/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var submission = await _context.Submissions
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Semester)
            .ThenInclude(s=> s.Module)
            .Include(s => s.SemesterStudent)
            .ThenInclude(s => s.Student)
            .Include(s => s.CFiles)
            .ThenInclude(c => c.ComparisonResults)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (submission == null)
        {
            return NotFound();
        }

        return View(submission);
    }

    // GET: Submission/Create/5
    public async Task<IActionResult> Create(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var semesterStudent = await _context.SemesterStudents
            .Include(s=> s.Student)
            .Include(s=> s.Semester)
            .ThenInclude(s=> s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (semesterStudent == null)
        {
            return NotFound();
        }

        ViewBag.SemesterStudent = semesterStudent;
        return View(new SubmissionForm());
    }

    // POST: Submission/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int id, [Bind("Name,ZipFile")] SubmissionForm submissionForm)
    {
        var semesterStudent = await _context.SemesterStudents
            .Include(s=> s.Student)
            .Include(s=> s.Semester)
            .ThenInclude(s=> s.Module)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (semesterStudent == null)
        {
            return NotFound();
        }
        
        if (!ModelState.IsValid)
        {
            ViewBag.SemesterStudent = semesterStudent;
            return View(submissionForm);
        }
        
        string fileNamePrefix = $"{semesterStudent.Student.Code}_{semesterStudent.Semester.Module.Code}";
        var submission = await _uploadHandler.ParseSubmission(submissionForm.Name, fileNamePrefix, submissionForm.ZipFile.OpenReadStream(),
            semesterStudent);

        // Compare submission with all other submissions
        _comparisonQueue.Enqueue(submission);

        return RedirectToAction(nameof(Details), new {Id = submission.Id});
    }

    // GET: Submission/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var submission = await _context.Submissions.FirstOrDefaultAsync(m => m.Id == id);
        if (submission == null)
        {
            return NotFound();
        }

        return View(submission);
    }

    // POST: Submission/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var submission = await _context.Submissions
            .Include(s => s.CFiles)
            .ThenInclude(c => c.ComparisonResults)
            .FirstOrDefaultAsync(s => s.Id == id);
        
        if (submission == null)
        {
            return NotFound();
        }
        
        foreach (var cFile in submission.CFiles) {
            foreach (var comparisonResult in cFile.ComparisonResults)
            {
                _context.ComparisonResults.Remove(comparisonResult);
            }
        }
        await _context.SaveChangesAsync();

        _context.Submissions.Remove(submission);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

src/PlagiarismCompare.Web/Views/Semester/Create.cshtml
@using PlagiarismCompare.Data.Models
@model PlagiarismCompare.Data.Models.Semester

@{
    ViewData["Title"] = "Create";
    Module module = ViewBag.Module;
}

<h1>Create Semester</h1>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <h5>Module</h5>
            <div class="form-group my-2">
                <label asp-for="Module.Code" class="control-label"></label>
                <input asp-for="Module.Code" class="form-control" value="@module.Code" readonly/>
                <span asp-validation-for="Module.Code" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Module.Name" class="control-label"></label>
                <input asp-for="Module.Name" class="form-control" value="@module.Name" readonly/>
                <span asp-validation-for="Module.Name" class="text-danger"></span>
            </div>
            
            <h5>Semester</h5>
            <div class="form-group my-2">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control"/>
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Term" class="control-label"></label>
                <select asp-for="Term" asp-items="Html.GetEnumSelectList<Term>()" class="form-control"></select>
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Module" asp-action="Index">Back to List</a>
</div>

src/PlagiarismCompare.Web/Views/Semester/Delete.cshtml
@model PlagiarismCompare.Data.Models.Semester

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Semester</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Semester</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Term)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/PlagiarismCompare.Web/Views/Semester/Details.cshtml
@model PlagiarismCompare.Data.Models.Semester

@{
    ViewData["Title"] = "Details";
}

<h1>Semester Details</h1>

<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Module.Code)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Module" asp-action="Details" asp-route-id="@Model.Module.Id">
                @Html.DisplayFor(model => model.Module.Code)
            </a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Module.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Module.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Term)
        </dd>
    </dl>
</div>

<div>
    <h4>Enrolled students</h4>
    <p>
        <a asp-controller="SemesterStudent" asp-action="CreateFromSemester" asp-route-id="@Model.Id">Enrol student</a>
    </p>
    <hr/>
    <table class="table">
        <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Code</th>
            <th>Student Id</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var semesterStudent in Model.SemesterStudents)
        {
            var student = semesterStudent.Student;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => student.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => student.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => student.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => student.StudentId)
                </td>
                <td>
                    <a asp-controller="Submission" asp-action="Create" asp-route-id="@semesterStudent.Id">Create submission</a> |
                    <a asp-controller="Student" asp-action="Details" asp-route-id="@student.Id">Student details</a> |
                    <a asp-controller="SemesterStudent" asp-action="Delete" asp-route-id="@semesterStudent.Id">Unenrol</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/PlagiarismCompare.Web/Views/Semester/Edit.cshtml
@using PlagiarismCompare.Data.Models
@model PlagiarismCompare.Data.Models.Semester

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Semester</h1>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <h5>Module</h5>
            <div class="form-group my-2">
                <label asp-for="Module.Code" class="control-label"></label>
                <input asp-for="Module.Code" class="form-control" value="@Model.Module.Code" readonly/>
                <span asp-validation-for="Module.Code" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Module.Name" class="control-label"></label>
                <input asp-for="Module.Name" class="form-control" value="@Model.Module.Name" readonly/>
                <span asp-validation-for="Module.Name" class="text-danger"></span>
            </div>
            
            <h5>Semester</h5>
            <div class="form-group my-2">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control"/>
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Term" class="control-label"></label>
                <select asp-for="Term" asp-items="Html.GetEnumSelectList<Term>()" class="form-control"></select>
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group my-2">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/PlagiarismCompare.Web/Views/Semester/Index.cshtml
@model IEnumerable<PlagiarismCompare.Data.Models.Semester>

@{
    ViewData["Title"] = "Semesters";
}

<h1>Semesters</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Module.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Module.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Term)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Module.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Module.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Term)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>